name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook=6.5.3
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=23.0.1
  - ydata-profiling=4.1.2
  - pyarrow=11.0.0
  - pip:
      - wandb==0.14.0