name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.2.2
  - ipython=8.12.0
  - notebook=6.5.3
  - jupyterlab=3.6.2
  - cookiecutter=2.1.1
  - hydra-core=1.0.6
  - matplotlib=3.7.1
  - pandas=1.5.3
  - git=2.40.0
  - pip=23.0.1
  - pip:
      - wandb==0.13.3
