name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - mlflow=2.2.2
  - scikit-learn=0.24.1
  - matplotlib=3.7.1
  - pillow=8.1.2
  - pip:
      - wandb==0.14.0
